/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4 at Sun Jan 03 21:49:57 2016. */

#ifndef PB_POCKETBOTPROTOCOL_PB_H_INCLUDED
#define PB_POCKETBOTPROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Face {
    int32_t id;
    float X;
    float Y;
    float Z;
} Face;

typedef struct _Gps {
    float lat;
    float lon;
} Gps;

typedef struct _Joystick {
    float X;
    float Y;
    float Z;
    bool A;
    bool B;
    int32_t heading;
} Joystick;

typedef struct _Control {
    Joystick joy1;
    Joystick joy2;
} Control;

typedef struct _Sensor {
    bool proximity;
    int32_t heading;
    Gps gps;
} Sensor;

typedef struct _PocketBotMessage {
    Face face;
    Control control;
    Sensor sensor;
} PocketBotMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PocketBotMessage_init_default            {Face_init_default, Control_init_default, Sensor_init_default}
#define Face_init_default                        {0, 0, 0, 0}
#define Sensor_init_default                      {0, 0, Gps_init_default}
#define Control_init_default                     {Joystick_init_default, Joystick_init_default}
#define Joystick_init_default                    {0, 0, 0, 0, 0, 0}
#define Gps_init_default                         {0, 0}
#define PocketBotMessage_init_zero               {Face_init_zero, Control_init_zero, Sensor_init_zero}
#define Face_init_zero                           {0, 0, 0, 0}
#define Sensor_init_zero                         {0, 0, Gps_init_zero}
#define Control_init_zero                        {Joystick_init_zero, Joystick_init_zero}
#define Joystick_init_zero                       {0, 0, 0, 0, 0, 0}
#define Gps_init_zero                            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Face_id_tag                              1
#define Face_X_tag                               2
#define Face_Y_tag                               3
#define Face_Z_tag                               4
#define Gps_lat_tag                              1
#define Gps_lon_tag                              2
#define Joystick_X_tag                           1
#define Joystick_Y_tag                           2
#define Joystick_Z_tag                           3
#define Joystick_A_tag                           4
#define Joystick_B_tag                           5
#define Joystick_heading_tag                     6
#define Control_joy1_tag                         1
#define Control_joy2_tag                         2
#define Sensor_proximity_tag                     1
#define Sensor_heading_tag                       2
#define Sensor_gps_tag                           3
#define PocketBotMessage_face_tag                1
#define PocketBotMessage_control_tag             2
#define PocketBotMessage_sensor_tag              3

/* Struct field encoding specification for nanopb */
extern const pb_field_t PocketBotMessage_fields[4];
extern const pb_field_t Face_fields[5];
extern const pb_field_t Sensor_fields[4];
extern const pb_field_t Control_fields[3];
extern const pb_field_t Joystick_fields[7];
extern const pb_field_t Gps_fields[3];

/* Maximum encoded size of messages (where known) */
#define PocketBotMessage_size                    116
#define Face_size                                21
#define Sensor_size                              25
#define Control_size                             64
#define Joystick_size                            30
#define Gps_size                                 10

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POCKETBOTPROTOCOL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
