/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4 at Sat Oct 31 20:57:45 2015. */

#ifndef PB_POCKETBOTPROTOCOL_PB_H_INCLUDED
#define PB_POCKETBOTPROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Control {
    float joyX;
    float joyY;
    float joyZ;
    bool buttonA;
    bool buttonB;
    int32_t destHeading;
} Control;

typedef struct _Face {
    int32_t faceId;
    float faceX;
    float faceY;
    float faceZ;
} Face;

typedef struct _Gps {
    float lat;
    float lon;
} Gps;

typedef struct _Sensor {
    bool proximity;
    int32_t heading;
} Sensor;

typedef struct _PocketBotMessage {
    Face face;
    Control control;
    Gps gps;
    Sensor sensor;
} PocketBotMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PocketBotMessage_init_default            {Face_init_default, Control_init_default, Gps_init_default, Sensor_init_default}
#define Face_init_default                        {0, 0, 0, 0}
#define Control_init_default                     {0, 0, 0, 0, 0, 0}
#define Gps_init_default                         {0, 0}
#define Sensor_init_default                      {0, 0}
#define PocketBotMessage_init_zero               {Face_init_zero, Control_init_zero, Gps_init_zero, Sensor_init_zero}
#define Face_init_zero                           {0, 0, 0, 0}
#define Control_init_zero                        {0, 0, 0, 0, 0, 0}
#define Gps_init_zero                            {0, 0}
#define Sensor_init_zero                         {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Control_joyX_tag                         1
#define Control_joyY_tag                         2
#define Control_joyZ_tag                         3
#define Control_buttonA_tag                      4
#define Control_buttonB_tag                      5
#define Control_destHeading_tag                  6
#define Face_faceId_tag                          1
#define Face_faceX_tag                           2
#define Face_faceY_tag                           3
#define Face_faceZ_tag                           4
#define Gps_lat_tag                              1
#define Gps_lon_tag                              2
#define Sensor_proximity_tag                     1
#define Sensor_heading_tag                       2
#define PocketBotMessage_face_tag                1
#define PocketBotMessage_control_tag             2
#define PocketBotMessage_gps_tag                 3
#define PocketBotMessage_sensor_tag              4

/* Struct field encoding specification for nanopb */
extern const pb_field_t PocketBotMessage_fields[5];
extern const pb_field_t Face_fields[5];
extern const pb_field_t Control_fields[7];
extern const pb_field_t Gps_fields[3];
extern const pb_field_t Sensor_fields[3];

/* Maximum encoded size of messages (where known) */
#define PocketBotMessage_size                    82
#define Face_size                                21
#define Control_size                             30
#define Gps_size                                 10
#define Sensor_size                              13

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POCKETBOTPROTOCOL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
