/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Sun Jan 03 21:49:57 2016. */

#include "PocketBotProtocol.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PocketBotMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, PocketBotMessage, face, face, &Face_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, PocketBotMessage, control, face, &Control_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, PocketBotMessage, sensor, control, &Sensor_fields),
    PB_LAST_FIELD
};

const pb_field_t Face_fields[5] = {
    PB_FIELD(  1, SINT32  , REQUIRED, STATIC  , FIRST, Face, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Face, X, id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Face, Y, X, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, Face, Z, Y, 0),
    PB_LAST_FIELD
};

const pb_field_t Sensor_fields[4] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, Sensor, proximity, proximity, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Sensor, heading, proximity, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, Sensor, gps, heading, &Gps_fields),
    PB_LAST_FIELD
};

const pb_field_t Control_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, Control, joy1, joy1, &Joystick_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, Control, joy2, joy1, &Joystick_fields),
    PB_LAST_FIELD
};

const pb_field_t Joystick_fields[7] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Joystick, X, X, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Joystick, Y, X, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Joystick, Z, Y, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, Joystick, A, Z, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, Joystick, B, A, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, Joystick, heading, B, 0),
    PB_LAST_FIELD
};

const pb_field_t Gps_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Gps, lat, lat, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Gps, lon, lat, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PocketBotMessage, face) < 65536 && pb_membersize(PocketBotMessage, control) < 65536 && pb_membersize(PocketBotMessage, sensor) < 65536 && pb_membersize(Sensor, gps) < 65536 && pb_membersize(Control, joy1) < 65536 && pb_membersize(Control, joy2) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PocketBotMessage_Face_Sensor_Control_Joystick_Gps)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PocketBotMessage, face) < 256 && pb_membersize(PocketBotMessage, control) < 256 && pb_membersize(PocketBotMessage, sensor) < 256 && pb_membersize(Sensor, gps) < 256 && pb_membersize(Control, joy1) < 256 && pb_membersize(Control, joy2) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PocketBotMessage_Face_Sensor_Control_Joystick_Gps)
#endif


